<?php

$html = '';
$html .= '<html>';
	$html .= '<head>';
		$html .= '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
		$html .= '<title>Título</title>';
	$html .= '</head>';
	$html .= '<body style="background-color: #ffffff; margin:0; padding:0; color: #777777;">';
		$html .= '<table background="'.$BASE_URL.'/img/correos/bg.jpg" width="600" height="501" align="center">';
			$html .= '<tr>';
				$html .= '<td valign="top">';
					$html .= '<table width="100%" border="0" cellspacing="0" cellpadding="0">';
						$html .= '<tbody>';
							$html .= '<tr>';
								$html .= '<td align="center">';
									$html .= '<table width="580">';
										$html .= '<tbody>';
											$html .= '<tr>';
												$html .= '<td align="left" style="padding-left:15px; padding-top:30px;"><a href=""><img src="'.$BASE_URL.'/img/correos/logo.png" style="border:none;display:block;" alt=""></a></td>';
											$html .= '</tr>';
										$html .= '</tbody>';
									$html .= '</table>';
								$html .= '</td>';
							$html .= '</tr>';
							$html .= '<tr>';
								$html .= '<td align="center" valign="top">';
									$html .= '<table width="558" border="0" cellspacing="0" cellpadding="0" style="width:558px;">';
										$html .= '<tbody>';
											$html .= '<tr>';
												$html .= '<td align="center" style="padding-top:25px; padding-bottom:30px;">';
													$html .= '<table width="513" cellspacing="0" cellpadding="0" border="0" style="font-family: &#39;Lucida Sans Unicode&#39;,&#39;Lucida Grande&#39;,sans-serif,Arial,Verdana; font-size: 12px;">';
														$html .= '<tr>';
															$html .= '<td colspan="3"><img src="'.$BASE_URL.'/img/correos/spacer.gif" style="display:block;" width="1" height="10" alt=""></td>';
														$html .= '</tr>';
														$html .= '<tr>';
															$html .= '<td valign="top">';
																$html .= '<p style="font-size: 17px; color: #000000; padding-top:5px;">Hola, <span style="color:#305D92;"></span></p>';
																$html .= '<p style="color:#000000;">Se ha detectado un tiempo de inactividad en Pron&oacute;sticos de '.$sLblMin.'.</p>';
																$html .= '<table style="">';
																	$html .= '<tr>';
																		$html .= '<td>';
																			$html .= '<div style="line-height:13px"><span style="font-size:12px; color:#000000;">Monto:</span> <span style="font-size:12px;"></span></div>';
																			$html .= '<div style="line-height:13px"><span style="font-size:12px; color:#000000;">&Uacute;ltima operaci&oacute;n:</span> <span style="font-size:12px;">'.$dFechaUltimaOperacion.'</span></div>';
																		$html .= '</td>';
																	$html .= '</tr>';
																$html .= '</table>';
															$html .= '</td>';
														$html .= '</tr>';
													$html .= '</table>';
												$html .= '</td>';
											$html .= '</tr>';
											$html .= '<tr>';
												$html .= '<td align="center" style="padding-top:10px;">';
													$html .= '&nbsp;';
												$html .= '</td>';
											$html .= '</tr>';
											$html .= '<tr>';
												$html .= '<td align="center" style="padding-top:10px;"> ';
													$html .= '&nbsp;';
												$html .= '</td>';
											$html .= '</tr>';
											$html .= '<tr>';
												$html .= '<td>';
													$html .= '<table width="510" align="center" border="0" cellspacing="0" cellpadding="0" style="font-family: &#39;Lucida Sans Unicode&#39;,&#39;Lucida Grande&#39;,sans-serif,Arial,Verdana; font-size: 12px;">';
														$html .= '<tbody>';
															$html .= '<tr>';
																$html .= '<td valign="top">';
																	$html .= '<p style="color:#3B669B;">';
																		$html .= '<span style="color:#000000">Red Efectiva</span>';
																		$html .= '<br/>';
																		$html .= 'Blvd. Antonio L. Rodr&iacute;guez 3058, Plaza Delphi,Col. Sta. Mar&iacute;a. Monterrey N.L. 64650';
																		$html .= '<br/>';
																		$html .= '<span style="color:#000000">T: </span>+52(81) 8356 2600';
																		$html .= '<br/>';
																		$html .= '<span style="color:#000000">E: </span><a href="mailto:sistemas@redefectiva.com" style="color: #04a8e3;">sistemas@redefectiva.com</a>';
																	$html .= '</p>';
																$html .= '</td>';
															$html .= '</tr> ';
															$html .= '<tr> ';
																$html .= '<td>&nbsp;</td>';
															$html .= '</tr> ';
														$html .= '</tbody>';
													$html .= '</table>';
												$html .= '</td>';
											$html .= '</tr>';
										$html .= '</tbody>';
									$html .= '</table>';
								$html .= '</td>';
							$html .= '</tr>';
						$html .= '</tbody>';
					$html .= '</table>';
				$html .= '</td>';
			$html .= '</tr>';
		$html .= '</table>';
	$html .= '</body>';
$html .= '</html>';
?>